// Grid layout positions for the constituency grid view, ported from the former
// lib/db seed data. electiondata.my does not provide geospatial/layout data —
// seats not listed here fall back to constituency-map.tsx's flow-grid layout.

interface GridPosition {
  gridX: number;
  gridY: number;
}

const SEAT_LAYOUT: Record<string, GridPosition> = {
  "Johor::N.01": { gridX: 7, gridY: 4 },
  "Johor::N.02": { gridX: 7, gridY: 5 },
  "Johor::N.03": { gridX: 8, gridY: 5 },
  "Johor::N.04": { gridX: 8, gridY: 6 },
  "Johor::N.05": { gridX: 9, gridY: 5 },
  "Johor::N.06": { gridX: 9, gridY: 6 },
  "Johor::N.07": { gridX: 8, gridY: 7 },
  "Johor::N.08": { gridX: 7, gridY: 7 },
  "Johor::N.09": { gridX: 7, gridY: 6 },
  "Johor::N.10": { gridX: 6, gridY: 6 },
  "Johor::N.11": { gridX: 6, gridY: 7 },
  "Johor::N.12": { gridX: 5, gridY: 8 },
  "Johor::N.13": { gridX: 6, gridY: 8 },
  "Johor::N.14": { gridX: 7, gridY: 8 },
  "Johor::N.15": { gridX: 5, gridY: 9 },
  "Johor::N.16": { gridX: 6, gridY: 9 },
  "Johor::N.17": { gridX: 7, gridY: 9 },
  "Johor::N.18": { gridX: 8, gridY: 8 },
  "Johor::N.19": { gridX: 9, gridY: 8 },
  "Johor::N.20": { gridX: 9, gridY: 9 },
  "Johor::N.21": { gridX: 8, gridY: 9 },
  "Johor::N.22": { gridX: 9, gridY: 10 },
  "Johor::N.23": { gridX: 8, gridY: 10 },
  "Johor::N.24": { gridX: 7, gridY: 10 },
  "Johor::N.25": { gridX: 7, gridY: 11 },
  "Johor::N.26": { gridX: 10, gridY: 9 },
  "Johor::N.27": { gridX: 11, gridY: 9 },
  "Johor::N.28": { gridX: 11, gridY: 8 },
  "Johor::N.29": { gridX: 10, gridY: 8 },
  "Johor::N.30": { gridX: 9, gridY: 7 },
  "Johor::N.31": { gridX: 10, gridY: 7 },
  "Johor::N.32": { gridX: 10, gridY: 6 },
  "Johor::N.33": { gridX: 12, gridY: 8 },
  "Johor::N.34": { gridX: 12, gridY: 9 },
  "Johor::N.35": { gridX: 12, gridY: 10 },
  "Johor::N.36": { gridX: 13, gridY: 9 },
  "Johor::N.37": { gridX: 13, gridY: 10 },
  "Johor::N.38": { gridX: 12, gridY: 11 },
  "Johor::N.39": { gridX: 13, gridY: 11 },
  "Johor::N.40": { gridX: 11, gridY: 11 },
  "Johor::N.41": { gridX: 10, gridY: 11 },
  "Johor::N.42": { gridX: 12, gridY: 12 },
  "Johor::N.43": { gridX: 12, gridY: 13 },
  "Johor::N.44": { gridX: 11, gridY: 12 },
  "Johor::N.45": { gridX: 11, gridY: 13 },
  "Johor::N.46": { gridX: 10, gridY: 13 },
  "Johor::N.47": { gridX: 10, gridY: 12 },
  "Johor::N.48": { gridX: 9, gridY: 12 },
  "Johor::N.49": { gridX: 9, gridY: 13 },
  "Johor::N.50": { gridX: 11, gridY: 10 },
  "Johor::N.51": { gridX: 10, gridY: 10 },
  "Johor::N.52": { gridX: 9, gridY: 11 },
  "Johor::N.53": { gridX: 8, gridY: 11 },
  "Johor::N.54": { gridX: 7, gridY: 12 },
  "Johor::N.55": { gridX: 8, gridY: 12 },
  "Johor::N.56": { gridX: 8, gridY: 13 },
  "Negeri Sembilan::N.01": { gridX: 8, gridY: 4 },
  "Negeri Sembilan::N.02": { gridX: 9, gridY: 4 },
  "Negeri Sembilan::N.03": { gridX: 10, gridY: 5 },
  "Negeri Sembilan::N.04": { gridX: 8, gridY: 5 },
  "Negeri Sembilan::N.05": { gridX: 11, gridY: 6 },
  "Negeri Sembilan::N.06": { gridX: 12, gridY: 6 },
  "Negeri Sembilan::N.07": { gridX: 11, gridY: 7 },
  "Negeri Sembilan::N.08": { gridX: 10, gridY: 6 },
  "Negeri Sembilan::N.09": { gridX: 7, gridY: 6 },
  "Negeri Sembilan::N.10": { gridX: 5, gridY: 7 },
  "Negeri Sembilan::N.11": { gridX: 6, gridY: 6 },
  "Negeri Sembilan::N.12": { gridX: 6, gridY: 7 },
  "Negeri Sembilan::N.13": { gridX: 7, gridY: 7 },
  "Negeri Sembilan::N.14": { gridX: 8, gridY: 7 },
  "Negeri Sembilan::N.15": { gridX: 9, gridY: 5 },
  "Negeri Sembilan::N.16": { gridX: 8, gridY: 6 },
  "Negeri Sembilan::N.17": { gridX: 10, gridY: 7 },
  "Negeri Sembilan::N.18": { gridX: 9, gridY: 6 },
  "Negeri Sembilan::N.19": { gridX: 9, gridY: 7 },
  "Negeri Sembilan::N.20": { gridX: 5, gridY: 8 },
  "Negeri Sembilan::N.21": { gridX: 6, gridY: 8 },
  "Negeri Sembilan::N.22": { gridX: 7, gridY: 8 },
  "Negeri Sembilan::N.23": { gridX: 7, gridY: 9 },
  "Negeri Sembilan::N.24": { gridX: 8, gridY: 8 },
  "Negeri Sembilan::N.25": { gridX: 9, gridY: 8 },
  "Negeri Sembilan::N.26": { gridX: 10, gridY: 8 },
  "Negeri Sembilan::N.27": { gridX: 8, gridY: 9 },
  "Negeri Sembilan::N.28": { gridX: 9, gridY: 9 },
  "Negeri Sembilan::N.29": { gridX: 5, gridY: 9 },
  "Negeri Sembilan::N.30": { gridX: 6, gridY: 9 },
  "Negeri Sembilan::N.31": { gridX: 7, gridY: 10 },
  "Negeri Sembilan::N.32": { gridX: 8, gridY: 10 },
  "Negeri Sembilan::N.33": { gridX: 6, gridY: 19 },
  "Negeri Sembilan::N.34": { gridX: 11, gridY: 8 },
  "Negeri Sembilan::N.35": { gridX: 11, gridY: 9 },
  "Negeri Sembilan::N.36": { gridX: 10, gridY: 9 },
};

export function getSeatLayout(state: string, code: string): GridPosition | null {
  return SEAT_LAYOUT[`${state}::${code}`] ?? null;
}

