// Which parliamentary constituency each state assembly (DUN) seat sits
// inside. Generated from electiondata.my's official delimitation boundary
// files (CC0), which carry a `parlimen` field on every DUN feature:
//   Peninsular Malaysia, 2018 delimitation
//     https://lake.electiondata.my/maps/delimitations/pen_dun.geojson
//   Sabah, 2019 delimitation
//     https://lake.electiondata.my/maps/delimitations/sabah_2019_dun.geojson
//   Sarawak, 2015 delimitation
//     https://lake.electiondata.my/maps/delimitations/sarawak_2015_dun.geojson
//
// Keyed by the seat string exactly as the API reports it ("N.01 Buloh
// Kasap") rather than by code alone. DUN codes are reused across
// delimitations for different seats, so requiring the name to match too
// means an election held under an older delimitation simply misses and
// falls back to state-level grouping, instead of being grouped wrongly.
//
// Regenerate by re-reading the boundary files above; do not hand-edit.
const SEAT_DISTRICTS: Record<string, Record<string, string>> = {
  "Johor": {
    "N.01 Buloh Kasap": "Segamat",
    "N.02 Jementah": "Segamat",
    "N.03 Pemanis": "Sekijang",
    "N.04 Kemelah": "Sekijang",
    "N.05 Tenang": "Labis",
    "N.06 Bekok": "Labis",
    "N.07 Bukit Kepong": "Pagoh",
    "N.08 Bukit Pasir": "Pagoh",
    "N.09 Gambir": "Ledang",
    "N.10 Tangkak": "Ledang",
    "N.11 Serom": "Ledang",
    "N.12 Bentayan": "Bakri",
    "N.13 Simpang Jeram": "Bakri",
    "N.14 Bukit Naning": "Bakri",
    "N.15 Maharani": "Muar",
    "N.16 Sungai Balang": "Muar",
    "N.17 Semerah": "Parit Sulong",
    "N.18 Sri Medan": "Parit Sulong",
    "N.19 Yong Peng": "Ayer Hitam",
    "N.20 Semarang": "Ayer Hitam",
    "N.21 Parit Yaani": "Sri Gading",
    "N.22 Parit Raja": "Sri Gading",
    "N.23 Penggaram": "Batu Pahat",
    "N.24 Senggarang": "Batu Pahat",
    "N.25 Rengit": "Batu Pahat",
    "N.26 Machap": "Simpang Renggam",
    "N.27 Layang-Layang": "Simpang Renggam",
    "N.28 Mengkibol": "Kluang",
    "N.29 Mahkota": "Kluang",
    "N.30 Paloh": "Sembrong",
    "N.31 Kahang": "Sembrong",
    "N.32 Endau": "Mersing",
    "N.33 Tenggaroh": "Mersing",
    "N.34 Panti": "Tenggara",
    "N.35 Pasir Raja": "Tenggara",
    "N.36 Sedili": "Kota Tinggi",
    "N.37 Johor Lama": "Kota Tinggi",
    "N.38 Penawar": "Pengerang",
    "N.39 Tanjung Surat": "Pengerang",
    "N.40 Tiram": "Tebrau",
    "N.41 Puteri Wangsa": "Tebrau",
    "N.42 Johor Jaya": "Pasir Gudang",
    "N.43 Permas": "Pasir Gudang",
    "N.44 Larkin": "Johor Bahru",
    "N.45 Stulang": "Johor Bahru",
    "N.46 Perling": "Pulai",
    "N.47 Kempas": "Pulai",
    "N.48 Skudai": "Iskandar Puteri",
    "N.49 Kota Iskandar": "Iskandar Puteri",
    "N.50 Bukit Permai": "Kulai",
    "N.51 Bukit Batu": "Kulai",
    "N.52 Senai": "Kulai",
    "N.53 Benut": "Pontian",
    "N.54 Pulai Sebatang": "Pontian",
    "N.55 Pekan Nanas": "Tanjung Piai",
    "N.56 Kukup": "Tanjung Piai",
  },
  "Kedah": {
    "N.01 Ayer Hangat": "Langkawi",
    "N.02 Kuah": "Langkawi",
    "N.03 Kota Siputeh": "Jerlun",
    "N.04 Ayer Hitam": "Jerlun",
    "N.05 Bukit Kayu Hitam": "Kubang Pasu",
    "N.06 Jitra": "Kubang Pasu",
    "N.07 Kuala Nerang": "Padang Terap",
    "N.08 Pedu": "Padang Terap",
    "N.09 Bukit Lada": "Pokok Sena",
    "N.10 Bukit Pinang": "Pokok Sena",
    "N.11 Derga": "Pokok Sena",
    "N.12 Suka Menanti": "Alor Setar",
    "N.13 Kota Darul Aman": "Alor Setar",
    "N.14 Alor Mengkudu": "Alor Setar",
    "N.15 Anak Bukit": "Kuala Kedah",
    "N.16 Kubang Rotan": "Kuala Kedah",
    "N.17 Pengkalan Kundor": "Kuala Kedah",
    "N.18 Tokai": "Pendang",
    "N.19 Sungai Tiang": "Pendang",
    "N.20 Sungai Limau": "Jerai",
    "N.21 Guar Chempedak": "Jerai",
    "N.22 Gurun": "Jerai",
    "N.23 Belantek": "Sik",
    "N.24 Jeneri": "Sik",
    "N.25 Bukit Selambau": "Merbok",
    "N.26 Tanjong Dawai": "Merbok",
    "N.27 Pantai Merdeka": "Sungai Petani",
    "N.28 Bakar Arang": "Sungai Petani",
    "N.29 Sidam": "Sungai Petani",
    "N.30 Bayu": "Baling",
    "N.31 Kupang": "Baling",
    "N.32 Kuala Ketil": "Baling",
    "N.33 Merbau Pulas": "Padang Serai",
    "N.34 Lunas": "Padang Serai",
    "N.35 Kulim": "Kulim-Bandar Baharu",
    "N.36 Bandar Baharu": "Kulim-Bandar Baharu",
  },
  "Kelantan": {
    "N.01 Pengkalan Kubor": "Tumpat",
    "N.02 Kelaboran": "Tumpat",
    "N.03 Pasir Pekan": "Tumpat",
    "N.04 Wakaf Bharu": "Tumpat",
    "N.05 Kijang": "Pengkalan Chepa",
    "N.06 Chempaka": "Pengkalan Chepa",
    "N.07 Panchor": "Pengkalan Chepa",
    "N.08 Tanjong Mas": "Kota Bharu",
    "N.09 Kota Lama": "Kota Bharu",
    "N.10 Bunut Payong": "Kota Bharu",
    "N.11 Tendong": "Pasir Mas",
    "N.12 Pengkalan Pasir": "Pasir Mas",
    "N.13 Meranti": "Pasir Mas",
    "N.14 Chetok": "Rantau Panjang",
    "N.15 Gual Periok": "Rantau Panjang",
    "N.16 Apam Putra": "Rantau Panjang",
    "N.17 Salor": "Kubang Kerian",
    "N.18 Pasir Tumboh": "Kubang Kerian",
    "N.19 Demit": "Kubang Kerian",
    "N.20 Tawang": "Bachok",
    "N.21 Pantai Irama": "Bachok",
    "N.22 Jelawat": "Bachok",
    "N.23 Melor": "Ketereh",
    "N.24 Kadok": "Ketereh",
    "N.25 Kok Lanas": "Ketereh",
    "N.26 Bukit Panau": "Tanah Merah",
    "N.27 Gual Ipoh": "Tanah Merah",
    "N.28 Kemahang": "Tanah Merah",
    "N.29 Selising": "Pasir Puteh",
    "N.30 Limbongan": "Pasir Puteh",
    "N.31 Semerak": "Pasir Puteh",
    "N.32 Gaal": "Pasir Puteh",
    "N.33 Pulai Chondong": "Machang",
    "N.34 Temangan": "Machang",
    "N.35 Kemuning": "Machang",
    "N.36 Bukit Bunga": "Jeli",
    "N.37 Air Lanas": "Jeli",
    "N.38 Kuala Balah": "Jeli",
    "N.39 Mengkebang": "Kuala Krai",
    "N.40 Guchil": "Kuala Krai",
    "N.41 Manek Urai": "Kuala Krai",
    "N.42 Dabong": "Kuala Krai",
    "N.43 Nenggiri": "Gua Musang",
    "N.44 Paloh": "Gua Musang",
    "N.45 Galas": "Gua Musang",
  },
  "Melaka": {
    "N.01 Kuala Linggi": "Masjid Tanah",
    "N.02 Tanjung Bidara": "Masjid Tanah",
    "N.03 Ayer Limau": "Masjid Tanah",
    "N.04 Lendu": "Masjid Tanah",
    "N.05 Taboh Naning": "Masjid Tanah",
    "N.06 Rembia": "Alor Gajah",
    "N.07 Gadek": "Alor Gajah",
    "N.08 Machap Jaya": "Alor Gajah",
    "N.09 Durian Tunggal": "Alor Gajah",
    "N.10 Asahan": "Alor Gajah",
    "N.11 Sungai Udang": "Tangga Batu",
    "N.12 Pantai Kundor": "Tangga Batu",
    "N.13 Paya Rumput": "Tangga Batu",
    "N.14 Kelebang": "Tangga Batu",
    "N.15 Pengkalan Batu": "Hang Tuah Jaya",
    "N.16 Ayer Keroh": "Hang Tuah Jaya",
    "N.17 Bukit Katil": "Hang Tuah Jaya",
    "N.18 Ayer Molek": "Hang Tuah Jaya",
    "N.19 Kesidang": "Kota Melaka",
    "N.20 Kota Laksamana": "Kota Melaka",
    "N.21 Duyong": "Kota Melaka",
    "N.22 Bandar Hilir": "Kota Melaka",
    "N.23 Telok Mas": "Kota Melaka",
    "N.24 Bemban": "Jasin",
    "N.25 Rim": "Jasin",
    "N.26 Serkam": "Jasin",
    "N.27 Merlimau": "Jasin",
    "N.28 Sungai Rambai": "Jasin",
  },
  "Negeri Sembilan": {
    "N.01 Chennah": "Jelebu",
    "N.02 Pertang": "Jelebu",
    "N.03 Sungai Lui": "Jelebu",
    "N.04 Klawang": "Jelebu",
    "N.05 Serting": "Jempol",
    "N.06 Palong": "Jempol",
    "N.07 Jeram Padang": "Jempol",
    "N.08 Bahau": "Jempol",
    "N.09 Lenggeng": "Seremban",
    "N.10 Nilai": "Seremban",
    "N.11 Lobak": "Seremban",
    "N.12 Temiang": "Seremban",
    "N.13 Sikamat": "Seremban",
    "N.14 Ampangan": "Seremban",
    "N.15 Juasseh": "Kuala Pilah",
    "N.16 Seri Menanti": "Kuala Pilah",
    "N.17 Senaling": "Kuala Pilah",
    "N.18 Pilah": "Kuala Pilah",
    "N.19 Johol": "Kuala Pilah",
    "N.20 Labu": "Rasah",
    "N.21 Bukit Kepayang": "Rasah",
    "N.22 Rahang": "Rasah",
    "N.23 Mambau": "Rasah",
    "N.24 Seremban Jaya": "Rasah",
    "N.25 Paroi": "Rembau",
    "N.26 Chembong": "Rembau",
    "N.27 Rantau": "Rembau",
    "N.28 Kota": "Rembau",
    "N.29 Chuah": "Port Dickson",
    "N.30 Lukut": "Port Dickson",
    "N.31 Bagan Pinang": "Port Dickson",
    "N.32 Linggi": "Port Dickson",
    "N.33 Sri Tanjung": "Port Dickson",
    "N.34 Gemas": "Tampin",
    "N.35 Gemencheh": "Tampin",
    "N.36 Repah": "Tampin",
  },
  "Pahang": {
    "N.01 Tanah Rata": "Cameron Highlands",
    "N.02 Jelai": "Cameron Highlands",
    "N.03 Padang Tengku": "Lipis",
    "N.04 Cheka": "Lipis",
    "N.05 Benta": "Lipis",
    "N.06 Batu Talam": "Raub",
    "N.07 Tras": "Raub",
    "N.08 Dong": "Raub",
    "N.09 Tahan": "Jerantut",
    "N.10 Damak": "Jerantut",
    "N.11 Pulau Tawar": "Jerantut",
    "N.12 Beserah": "Indera Mahkota",
    "N.13 Semambu": "Indera Mahkota",
    "N.14 Teruntum": "Kuantan",
    "N.15 Tanjung Lumpur": "Kuantan",
    "N.16 Inderapura": "Kuantan",
    "N.17 Sungai Lembing": "Paya Besar",
    "N.18 Lepar": "Paya Besar",
    "N.19 Panching": "Paya Besar",
    "N.20 Pulau Manis": "Pekan",
    "N.21 Peramu Jaya": "Pekan",
    "N.22 Bebar": "Pekan",
    "N.23 Chini": "Pekan",
    "N.24 Luit": "Maran",
    "N.25 Kuala Sentul": "Maran",
    "N.26 Chenor": "Maran",
    "N.27 Jenderak": "Kuala Krau",
    "N.28 Kerdau": "Kuala Krau",
    "N.29 Jengka": "Kuala Krau",
    "N.30 Mentakab": "Temerloh",
    "N.31 Lanchang": "Temerloh",
    "N.32 Kuala Semantan": "Temerloh",
    "N.33 Bilut": "Bentong",
    "N.34 Ketari": "Bentong",
    "N.35 Sabai": "Bentong",
    "N.36 Pelangai": "Bentong",
    "N.37 Guai": "Bera",
    "N.38 Triang": "Bera",
    "N.39 Kemayan": "Bera",
    "N.40 Bukit Ibam": "Rompin",
    "N.41 Muadzam Shah": "Rompin",
    "N.42 Tioman": "Rompin",
  },
  "Perak": {
    "N.01 Pengkalan Hulu": "Gerik",
    "N.02 Temengor": "Gerik",
    "N.03 Kenering": "Lenggong",
    "N.04 Kota Tampan": "Lenggong",
    "N.05 Selama": "Larut",
    "N.06 Kubu Gajah": "Larut",
    "N.07 Batu Kurau": "Larut",
    "N.08 Titi Serong": "Parit Buntar",
    "N.09 Kuala Kurau": "Parit Buntar",
    "N.10 Alor Pongsu": "Bagan Serai",
    "N.11 Gunong Semanggol": "Bagan Serai",
    "N.12 Selinsing": "Bagan Serai",
    "N.13 Kuala Sepetang": "Bukit Gantang",
    "N.14 Changkat Jering": "Bukit Gantang",
    "N.15 Trong": "Bukit Gantang",
    "N.16 Kamunting": "Taiping",
    "N.17 Pokok Assam": "Taiping",
    "N.18 Aulong": "Taiping",
    "N.19 Chenderoh": "Padang Rengas",
    "N.20 Lubok Merbau": "Padang Rengas",
    "N.21 Lintang": "Sungai Siput",
    "N.22 Jalong": "Sungai Siput",
    "N.23 Manjoi": "Tambun",
    "N.24 Hulu Kinta": "Tambun",
    "N.25 Canning": "Ipoh Timor",
    "N.26 Tebing Tinggi": "Ipoh Timor",
    "N.27 Pasir Pinji": "Ipoh Timor",
    "N.28 Bercham": "Ipoh Barat",
    "N.29 Kepayang": "Ipoh Barat",
    "N.30 Buntong": "Ipoh Barat",
    "N.31 Jelapang": "Batu Gajah",
    "N.32 Menglembu": "Batu Gajah",
    "N.33 Tronoh": "Batu Gajah",
    "N.34 Bukit Chandan": "Kuala Kangsar",
    "N.35 Manong": "Kuala Kangsar",
    "N.36 Pengkalan Baharu": "Beruas",
    "N.37 Pantai Remis": "Beruas",
    "N.38 Astaka": "Beruas",
    "N.39 Belanja": "Parit",
    "N.40 Bota": "Parit",
    "N.41 Malim Nawar": "Kampar",
    "N.42 Keranji": "Kampar",
    "N.43 Tualang Sekah": "Kampar",
    "N.44 Sungai Rapat": "Gopeng",
    "N.45 Simpang Pulai": "Gopeng",
    "N.46 Teja": "Gopeng",
    "N.47 Chenderiang": "Tapah",
    "N.48 Ayer Kuning": "Tapah",
    "N.49 Sungai Manik": "Pasir Salak",
    "N.50 Kampong Gajah": "Pasir Salak",
    "N.51 Pasir Panjang": "Lumut",
    "N.52 Pangkor": "Lumut",
    "N.53 Rungkup": "Bagan Datuk",
    "N.54 Hutan Melintang": "Bagan Datuk",
    "N.55 Pasir Bedamar": "Teluk Intan",
    "N.56 Changkat Jong": "Teluk Intan",
    "N.57 Sungkai": "Tanjong Malim",
    "N.58 Slim": "Tanjong Malim",
    "N.59 Behrang": "Tanjong Malim",
  },
  "Perlis": {
    "N.01 Titi Tinggi": "Padang Besar",
    "N.02 Beseri": "Padang Besar",
    "N.03 Chuping": "Padang Besar",
    "N.04 Mata Ayer": "Padang Besar",
    "N.05 Santan": "Padang Besar",
    "N.06 Bintong": "Kangar",
    "N.07 Sena": "Kangar",
    "N.08 Indera Kayangan": "Kangar",
    "N.09 Kuala Perlis": "Kangar",
    "N.10 Kayang": "Kangar",
    "N.11 Pauh": "Arau",
    "N.12 Tambun Tulang": "Arau",
    "N.13 Guar Sanji": "Arau",
    "N.14 Simpang Empat": "Arau",
    "N.15 Sanglang": "Arau",
  },
  "Pulau Pinang": {
    "N.01 Penaga": "Kepala Batas",
    "N.02 Bertam": "Kepala Batas",
    "N.03 Pinang Tunggal": "Kepala Batas",
    "N.04 Permatang Berangan": "Tasek Gelugor",
    "N.05 Sungai Dua": "Tasek Gelugor",
    "N.06 Telok Ayer Tawar": "Tasek Gelugor",
    "N.07 Sungai Puyu": "Bagan",
    "N.08 Bagan Jermal": "Bagan",
    "N.09 Bagan Dalam": "Bagan",
    "N.10 Seberang Jaya": "Permatang Pauh",
    "N.11 Permatang Pasir": "Permatang Pauh",
    "N.12 Penanti": "Permatang Pauh",
    "N.13 Berapit": "Bukit Mertajam",
    "N.14 Machang Bubuk": "Bukit Mertajam",
    "N.15 Padang Lalang": "Bukit Mertajam",
    "N.16 Perai": "Batu Kawan",
    "N.17 Bukit Tengah": "Batu Kawan",
    "N.18 Bukit Tambun": "Batu Kawan",
    "N.19 Jawi": "Nibong Tebal",
    "N.20 Sungai Bakap": "Nibong Tebal",
    "N.21 Sungai Acheh": "Nibong Tebal",
    "N.22 Tanjong Bunga": "Bukit Bendera",
    "N.23 Air Putih": "Bukit Bendera",
    "N.24 Kebun Bunga": "Bukit Bendera",
    "N.25 Pulau Tikus": "Bukit Bendera",
    "N.26 Padang Kota": "Tanjong",
    "N.27 Pengkalan Kota": "Tanjong",
    "N.28 Komtar": "Tanjong",
    "N.29 Datok Keramat": "Jelutong",
    "N.30 Sungai Pinang": "Jelutong",
    "N.31 Batu Lancang": "Jelutong",
    "N.32 Seri Delima": "Bukit Gelugor",
    "N.33 Air Itam": "Bukit Gelugor",
    "N.34 Paya Terubong": "Bukit Gelugor",
    "N.35 Batu Uban": "Bayan Baru",
    "N.36 Pantai Jerejak": "Bayan Baru",
    "N.37 Batu Maung": "Bayan Baru",
    "N.38 Bayan Lepas": "Balik Pulau",
    "N.39 Pulau Betong": "Balik Pulau",
    "N.40 Telok Bahang": "Balik Pulau",
  },
  "Sabah": {
    "N.01 Banggi": "Kudat",
    "N.02 Bengkoka": "Kudat",
    "N.03 Pitas": "Kudat",
    "N.04 Tanjong Kapor": "Kudat",
    "N.05 Matunggong": "Kota Marudu",
    "N.06 Bandau": "Kota Marudu",
    "N.07 Tandek": "Kota Marudu",
    "N.08 Pintasan": "Kota Belud",
    "N.09 Tempasuk": "Kota Belud",
    "N.10 Usukan": "Kota Belud",
    "N.11 Kadamaian": "Kota Belud",
    "N.12 Sulaman": "Tuaran",
    "N.13 Pantai Dalit": "Tuaran",
    "N.14 Tamparuli": "Tuaran",
    "N.15 Kiulu": "Tuaran",
    "N.16 Karambunai": "Sepanggar",
    "N.17 Darau": "Sepanggar",
    "N.18 Inanam": "Sepanggar",
    "N.19 Likas": "Kota Kinabalu",
    "N.20 Api-Api": "Kota Kinabalu",
    "N.21 Luyang": "Kota Kinabalu",
    "N.22 Tanjung Aru": "Putatan",
    "N.23 Petagas": "Putatan",
    "N.24 Tanjung Keramat": "Putatan",
    "N.25 Kapayan": "Penampang",
    "N.26 Moyog": "Penampang",
    "N.27 Limbahau": "Papar",
    "N.28 Kawang": "Papar",
    "N.29 Pantai Manis": "Papar",
    "N.30 Bongawan": "Kimanis",
    "N.31 Membakut": "Kimanis",
    "N.32 Klias": "Beaufort",
    "N.33 Kuala Penyu": "Beaufort",
    "N.34 Lumadan": "Sipitang",
    "N.35 Sindumin": "Sipitang",
    "N.36 Kundasang": "Ranau",
    "N.37 Karanaan": "Ranau",
    "N.38 Paginatan": "Ranau",
    "N.39 Tambunan": "Keningau",
    "N.40 Bingkor": "Keningau",
    "N.41 Liawan": "Keningau",
    "N.42 Melalap": "Tenom",
    "N.43 Kemabong": "Tenom",
    "N.44 Tulid": "Pensiangan",
    "N.45 Sook": "Pensiangan",
    "N.46 Nabawan": "Pensiangan",
    "N.47 Telupid": "Beluran",
    "N.48 Sugut": "Beluran",
    "N.49 Labuk": "Beluran",
    "N.50 Gum-Gum": "Libaran",
    "N.51 Sungai Manila": "Libaran",
    "N.52 Sungai Sibuga": "Libaran",
    "N.53 Sekong": "Batu Sapi",
    "N.54 Karamunting": "Batu Sapi",
    "N.55 Elopura": "Sandakan",
    "N.56 Tanjong Papat": "Sandakan",
    "N.57 Kuamut": "Kinabatangan",
    "N.58 Lamag": "Kinabatangan",
    "N.59 Sukau": "Kinabatangan",
    "N.60 Tungku": "Lahad Datu",
    "N.61 Segama": "Lahad Datu",
    "N.62 Silam": "Lahad Datu",
    "N.63 Kunak": "Lahad Datu",
    "N.64 Sulabayan": "Semporna",
    "N.65 Senallang": "Semporna",
    "N.66 Bugaya": "Semporna",
    "N.67 Balung": "Tawau",
    "N.68 Apas": "Tawau",
    "N.69 Sri Tanjong": "Tawau",
    "N.70 Kukusan": "Kalabakan",
    "N.71 Tanjung Batu": "Kalabakan",
    "N.72 Merotai": "Kalabakan",
    "N.73 Sebatik": "Kalabakan",
  },
  "Sarawak": {
    "N.01 Opar": "Mas Gading",
    "N.02 Tasik Biru": "Mas Gading",
    "N.03 Tanjong Datu": "Santubong",
    "N.04 Pantai Damai": "Santubong",
    "N.05 Demak Laut": "Santubong",
    "N.06 Tupong": "Petra Jaya",
    "N.07 Samariang": "Petra Jaya",
    "N.08 Satok": "Petra Jaya",
    "N.09 Padungan": "Bandar Kuching",
    "N.10 Pending": "Bandar Kuching",
    "N.11 Batu Lintang": "Bandar Kuching",
    "N.12 Kota Sentosa": "Stampin",
    "N.13 Batu Kitang": "Stampin",
    "N.14 Batu Kawah": "Stampin",
    "N.15 Asajaya": "Kota Samarahan",
    "N.16 Muara Tuang": "Kota Samarahan",
    "N.17 Stakan": "Kota Samarahan",
    "N.18 Serembu": "Puncak Borneo",
    "N.19 Mambong": "Puncak Borneo",
    "N.20 Tarat": "Puncak Borneo",
    "N.21 Tebedu": "Serian",
    "N.22 Kedup": "Serian",
    "N.23 Bukit Semuja": "Serian",
    "N.24 Sadong Jaya": "Batang Sadong",
    "N.25 Simunjan": "Batang Sadong",
    "N.26 Gedong": "Batang Sadong",
    "N.27 Sebuyau": "Batang Lupar",
    "N.28 Lingga": "Batang Lupar",
    "N.29 Beting Maro": "Batang Lupar",
    "N.30 Balai Ringin": "Sri Aman",
    "N.31 Bukit Begunan": "Sri Aman",
    "N.32 Simanggang": "Sri Aman",
    "N.33 Engkilili": "Lubok Antu",
    "N.34 Batang Ai": "Lubok Antu",
    "N.35 Saribas": "Betong",
    "N.36 Layar": "Betong",
    "N.37 Bukit Saban": "Betong",
    "N.38 Kalaka": "Saratok",
    "N.39 Krian": "Saratok",
    "N.40 Kabong": "Saratok",
    "N.41 Kuala Rajang": "Tanjong Manis",
    "N.42 Semop": "Tanjong Manis",
    "N.43 Daro": "Igan",
    "N.44 Jemoreng": "Igan",
    "N.45 Repok": "Sarikei",
    "N.46 Meradong": "Sarikei",
    "N.47 Pakan": "Julau",
    "N.48 Meluan": "Julau",
    "N.49 Ngemah": "Kanowit",
    "N.50 Machan": "Kanowit",
    "N.51 Bukit Assek": "Lanang",
    "N.52 Dudong": "Lanang",
    "N.53 Bawang Assan": "Sibu",
    "N.54 Pelawan": "Sibu",
    "N.55 Nangka": "Sibu",
    "N.56 Dalat": "Mukah",
    "N.57 Tellian": "Mukah",
    "N.58 Balingian": "Mukah",
    "N.59 Tamin": "Selangau",
    "N.60 Kakus": "Selangau",
    "N.61 Pelagus": "Kapit",
    "N.62 Katibas": "Kapit",
    "N.63 Bukit Goram": "Kapit",
    "N.64 Baleh": "Hulu Rajang",
    "N.65 Belaga": "Hulu Rajang",
    "N.66 Murum": "Hulu Rajang",
    "N.67 Jepak": "Bintulu",
    "N.68 Tanjong Batu": "Bintulu",
    "N.69 Kemena": "Bintulu",
    "N.70 Samalaju": "Bintulu",
    "N.71 Bekenu": "Sibuti",
    "N.72 Lambir": "Sibuti",
    "N.73 Piasau": "Miri",
    "N.74 Pujut": "Miri",
    "N.75 Senadin": "Miri",
    "N.76 Marudi": "Baram",
    "N.77 Telang Usan": "Baram",
    "N.78 Mulu": "Baram",
    "N.79 Bukit Kota": "Limbang",
    "N.80 Batu Danau": "Limbang",
    "N.81 Ba'kelalan": "Lawas",
    "N.82 Bukit Sari": "Lawas",
  },
  "Selangor": {
    "N.01 Sungai Air Tawar": "Sabak Bernam",
    "N.02 Sabak": "Sabak Bernam",
    "N.03 Sungai Panjang": "Sungai Besar",
    "N.04 Sekinchan": "Sungai Besar",
    "N.05 Hulu Bernam": "Hulu Selangor",
    "N.06 Kuala Kubu Baharu": "Hulu Selangor",
    "N.07 Batang Kali": "Hulu Selangor",
    "N.08 Sungai Burong": "Tanjong Karang",
    "N.09 Permatang": "Tanjong Karang",
    "N.10 Bukit Melawati": "Kuala Selangor",
    "N.11 Ijok": "Kuala Selangor",
    "N.12 Jeram": "Kuala Selangor",
    "N.13 Kuang": "Selayang",
    "N.14 Rawang": "Selayang",
    "N.15 Taman Templer": "Selayang",
    "N.16 Sungai Tua": "Gombak",
    "N.17 Gombak Setia": "Gombak",
    "N.18 Hulu Kelang": "Gombak",
    "N.19 Bukit Antarabangsa": "Ampang",
    "N.20 Lembah Jaya": "Ampang",
    "N.21 Pandan Indah": "Pandan",
    "N.22 Teratai": "Pandan",
    "N.23 Dusun Tua": "Hulu Langat",
    "N.24 Semenyih": "Hulu Langat",
    "N.25 Kajang": "Bangi",
    "N.26 Sungai Ramal": "Bangi",
    "N.27 Balakong": "Bangi",
    "N.28 Seri Kembangan": "Puchong",
    "N.29 Seri Serdang": "Puchong",
    "N.30 Kinrara": "Subang",
    "N.31 Subang Jaya": "Subang",
    "N.32 Seri Setia": "Petaling Jaya",
    "N.33 Taman Medan": "Petaling Jaya",
    "N.34 Bukit Gasing": "Petaling Jaya",
    "N.35 Kampung Tunku": "Damansara",
    "N.36 Bandar Utama": "Damansara",
    "N.37 Bukit Lanjan": "Damansara",
    "N.38 Paya Jaras": "Sungai Buloh",
    "N.39 Kota Damansara": "Sungai Buloh",
    "N.40 Kota Anggerik": "Shah Alam",
    "N.41 Batu Tiga": "Shah Alam",
    "N.42 Meru": "Kapar",
    "N.43 Sementa": "Kapar",
    "N.44 Selat Klang": "Kapar",
    "N.45 Bandar Baru Klang": "Klang",
    "N.46 Pelabuhan Klang": "Klang",
    "N.47 Pandamaran": "Klang",
    "N.48 Sentosa": "Kota Raja",
    "N.49 Sungai Kandis": "Kota Raja",
    "N.50 Kota Kemuning": "Kota Raja",
    "N.51 Sijangkang": "Kuala Langat",
    "N.52 Banting": "Kuala Langat",
    "N.53 Morib": "Kuala Langat",
    "N.54 Tanjong Sepat": "Sepang",
    "N.55 Dengkil": "Sepang",
    "N.56 Sungai Pelek": "Sepang",
  },
  "Terengganu": {
    "N.01 Kuala Besut": "Besut",
    "N.02 Kota Putera": "Besut",
    "N.03 Jertih": "Besut",
    "N.04 Hulu Besut": "Besut",
    "N.05 Jabi": "Setiu",
    "N.06 Permaisuri": "Setiu",
    "N.07 Langkap": "Setiu",
    "N.08 Batu Rakit": "Setiu",
    "N.09 Tepuh": "Kuala Nerus",
    "N.10 Buluh Gading": "Kuala Nerus",
    "N.11 Seberang Takir": "Kuala Nerus",
    "N.12 Bukit Tunggal": "Kuala Nerus",
    "N.13 Wakaf Mempelam": "Kuala Terengganu",
    "N.14 Bandar": "Kuala Terengganu",
    "N.15 Ladang": "Kuala Terengganu",
    "N.16 Batu Buruk": "Kuala Terengganu",
    "N.17 Alur Limbat": "Marang",
    "N.18 Bukit Payung": "Marang",
    "N.19 Ru Rendang": "Marang",
    "N.20 Pengkalan Berangan": "Marang",
    "N.21 Telemung": "Hulu Terengganu",
    "N.22 Manir": "Hulu Terengganu",
    "N.23 Kuala Berang": "Hulu Terengganu",
    "N.24 Ajil": "Hulu Terengganu",
    "N.25 Bukit Besi": "Dungun",
    "N.26 Rantau Abang": "Dungun",
    "N.27 Sura": "Dungun",
    "N.28 Paka": "Dungun",
    "N.29 Kemasik": "Kemaman",
    "N.30 Kijal": "Kemaman",
    "N.31 Cukai": "Kemaman",
    "N.32 Air Putih": "Kemaman",
  },
};

export function getSeatDistrict(state: string, code: string, name: string): string | null {
  return SEAT_DISTRICTS[state]?.[`${code} ${name}`] ?? null;
}
