// Parliamentary-constituency (district) name per DUN seat, ported from the
// former lib/db seed data. electiondata.my's API exposes no DUN-to-parliament
// containment relationship, so this only covers Johor and Negeri Sembilan —
// the two states whose seed district names are verified against the real
// parliamentary constituency names. Seats not listed here fall back to
// grouping by state, same as before.

const SEAT_DISTRICTS: Record<string, string> = {
  "Johor::N.01": "Segamat",
  "Johor::N.02": "Segamat",
  "Johor::N.03": "Sekijang",
  "Johor::N.04": "Sekijang",
  "Johor::N.05": "Labis",
  "Johor::N.06": "Labis",
  "Johor::N.07": "Pagoh",
  "Johor::N.08": "Pagoh",
  "Johor::N.09": "Ledang",
  "Johor::N.10": "Ledang",
  "Johor::N.11": "Ledang",
  "Johor::N.12": "Bakri",
  "Johor::N.13": "Bakri",
  "Johor::N.14": "Bakri",
  "Johor::N.15": "Muar",
  "Johor::N.16": "Muar",
  "Johor::N.17": "Parit Sulong",
  "Johor::N.18": "Parit Sulong",
  "Johor::N.19": "Ayer Hitam",
  "Johor::N.20": "Ayer Hitam",
  "Johor::N.21": "Sri Gading",
  "Johor::N.22": "Sri Gading",
  "Johor::N.23": "Batu Pahat",
  "Johor::N.24": "Batu Pahat",
  "Johor::N.25": "Batu Pahat",
  "Johor::N.26": "Simpang Renggam",
  "Johor::N.27": "Simpang Renggam",
  "Johor::N.28": "Kluang",
  "Johor::N.29": "Kluang",
  "Johor::N.30": "Sembrong",
  "Johor::N.31": "Sembrong",
  "Johor::N.32": "Mersing",
  "Johor::N.33": "Mersing",
  "Johor::N.34": "Tenggara",
  "Johor::N.35": "Tenggara",
  "Johor::N.36": "Kota Tinggi",
  "Johor::N.37": "Kota Tinggi",
  "Johor::N.38": "Pengerang",
  "Johor::N.39": "Pengerang",
  "Johor::N.40": "Tebrau",
  "Johor::N.41": "Tebrau",
  "Johor::N.42": "Pasir Gudang",
  "Johor::N.43": "Pasir Gudang",
  "Johor::N.44": "Johor Bahru",
  "Johor::N.45": "Pulai",
  "Johor::N.46": "Johor Bahru",
  "Johor::N.47": "Pulai",
  "Johor::N.48": "Iskandar Puteri",
  "Johor::N.49": "Iskandar Puteri",
  "Johor::N.50": "Kulai",
  "Johor::N.51": "Kulai",
  "Johor::N.52": "Kulai",
  "Johor::N.53": "Pontian",
  "Johor::N.54": "Pontian",
  "Johor::N.55": "Tanjung Piai",
  "Johor::N.56": "Tanjung Piai",
  "Negeri Sembilan::N.01": "Jelebu",
  "Negeri Sembilan::N.02": "Jelebu",
  "Negeri Sembilan::N.03": "Jelebu",
  "Negeri Sembilan::N.04": "Jelebu",
  "Negeri Sembilan::N.05": "Jempol",
  "Negeri Sembilan::N.06": "Jempol",
  "Negeri Sembilan::N.07": "Jempol",
  "Negeri Sembilan::N.08": "Jempol",
  "Negeri Sembilan::N.09": "Seremban",
  "Negeri Sembilan::N.10": "Seremban",
  "Negeri Sembilan::N.11": "Seremban",
  "Negeri Sembilan::N.12": "Seremban",
  "Negeri Sembilan::N.13": "Seremban",
  "Negeri Sembilan::N.14": "Seremban",
  "Negeri Sembilan::N.15": "Kuala Pilah",
  "Negeri Sembilan::N.16": "Kuala Pilah",
  "Negeri Sembilan::N.17": "Kuala Pilah",
  "Negeri Sembilan::N.18": "Kuala Pilah",
  "Negeri Sembilan::N.19": "Kuala Pilah",
  "Negeri Sembilan::N.20": "Rasah",
  "Negeri Sembilan::N.21": "Rasah",
  "Negeri Sembilan::N.22": "Rasah",
  "Negeri Sembilan::N.23": "Rasah",
  "Negeri Sembilan::N.24": "Rasah",
  "Negeri Sembilan::N.25": "Rembau",
  "Negeri Sembilan::N.26": "Rembau",
  "Negeri Sembilan::N.27": "Rembau",
  "Negeri Sembilan::N.28": "Rembau",
  "Negeri Sembilan::N.29": "Port Dickson",
  "Negeri Sembilan::N.30": "Port Dickson",
  "Negeri Sembilan::N.31": "Port Dickson",
  "Negeri Sembilan::N.32": "Port Dickson",
  "Negeri Sembilan::N.33": "Port Dickson",
  "Negeri Sembilan::N.34": "Tampin",
  "Negeri Sembilan::N.35": "Tampin",
  "Negeri Sembilan::N.36": "Tampin",
};

export function getSeatDistrict(state: string, code: string): string | null {
  return SEAT_DISTRICTS[`${state}::${code}`] ?? null;
}

